version: "3.8"

networks:
  app_network: # Define a custom network
    driver: bridge

services:
  recommender_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
          - tripweaver
    ports:
      - "8001:8000" # Map the host port 8001 to the container port 8000
    networks: 
      - app_network

  tripweaver:
    container_name: tripweaver
    image: tripweaver-image
    build: .
    ports:
      - "3000:3000"
    networks: 
      - app_network