version: "3.8"

networks:
  app_network: # Define a custom network
    driver: bridge

services:
  recommender_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
          - tripweaver
    ports:
      - "8001:8000" # Map the host port 8001 to the container port 8000
    networks: git
      - app_network

  
  # will remove this service later since tripweaver api is deployed
  tripweaver:
    container_name: tripweaver
    image: tripweaver-image # use existing image, do NOT rebuild
    ports:
      - "3000:3000"
    networks: 
      - app_network