version: "3.8"

services:
  recommender_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000" # Map the host port 8001 to the container port 8000
    volumes:
      - ./api/Hybrid_Recommendation_System:/recommender_api # Sync the app code for easier updates
      - .env:/.env # Load environment variables from a file on the host machine

    # working_dir: /recommender_api # Set the correct working directory
    env_file: ".env"

    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]